name: Build and Deploy Docker Image with self hosted runner

on:
  push:
    branches:
      - main   # Trigger on push to the main branch
  pull_request:
    branches:
      - main   # Trigger on pull request to the main branch

jobs:
  build:
    runs-on:
     - self-hosted   # You can change this to another runner if needed

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg firstName="${{ vars.FIRST_NAME }}" --build-arg lastName="${{ vars.LAST_NAME }}" -t api_starter .
       # Run Docker container with environment variables passed at runtime
      - name: Run Docker container with environment variables
        run: |
              docker stop api_starter_container
              docker rm api_starter_container
              docker run -d -p 8080:8080 \
              -e firstName="${{ vars.FIRST_NAME }}" \
              -e lastName="${{ vars.LAST_NAME }}" \
              --name api_starter_container ${{ secrets.DOCKER_USERNAME }}/api_starter

    #   Push Docker image to Docker Hub (if desired)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag api_starter:latest ${{ secrets.DOCKER_USERNAME }}/api_starter:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api_starter:latest
